osx_image: xcode7.3

git:
  depth: 5

branches:
  only:
    - /^deploy.*$/

os:
  - osx

language: c

cache:
  directories:
    - electron-cloud-deploy-cache
    - build/cache
    - node_modules
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar 

before_install:
  # homebrew
  - brew update --verbose
  # ruby
  - rvm get stable --auto-dotfiles
  # node
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR=$HOME/.nvm sh
  - source $HOME/.nvm/nvm.sh
  - command -v nvm
  - nvm install 6.3.1
  - nvm use 6.3.1
  
install:
  - npm prune
  - npm install

before_script:
  # ecd:cache:get
  - npm run-script cache-get

script:
  - npm run-script build
  # ecd:app:deploy
  - npm run-script deploy-bintray
  - npm run-script deploy-github

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: always

